### ISSUE TITLE
when i build your project i am getting some errors 

### ISSUE THREAD

**Issue by elvanduman71** [kmyid/fastMCD#5]
i have used vs 2012 and vs 2015, opencv 3.2, cmake 3.8 in win 10 operation system. But i am getting some error.

when i click configure button via CMAKE i am getting the message below :
<<
CMake Warning at C:/opencv/build/OpenCVConfig.cmake:138 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)
>>

when building project on Visual Studio, i am getting many errors.

i wonder which version of vs ,opencv, and cmake should i use?
Thanks

**Comment by kmyi** [comment]
Hi Elvan

I got your e-mail :-) I'll just reply here directly. I don't have a windows environment, and I've tested the code on both Linux and OSX. In case of windows, I cannot help you much. However, it should work with OpenCV 2.4.12. Also, in your case, it seems CMAKE cannot find opencv. Also, the other problems you mentioned in your email seems to be due to std libraries not being included properly. Sorry that I could not help you more.

**Comment by elvanduman71** [comment]
Thanks for your help ,

Yesterday I have tried to setup the project on ubuntu 16.04 with the same version of opencv

**when i write "cmake .. "  i am getting the error below :** 

> cmake ..
> -- OpenCV ARCH: 
> -- OpenCV RUNTIME: 
> -- OpenCV STATIC: OFF
> CMake Warning at /home/elvan/opencv-2.4.12/cmake/OpenCVConfig.cmake:163 (message):
>   Found OpenCV Windows Pack but it has not binaries compatible with your
>   configuration.
> 
>   You should manually point CMake variable OpenCV_DIR to your build of OpenCV
>   library.
> Call Stack (most recent call first):
>   CMakeLists.txt:11 (find_package)
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/elvan/fastMCD/build

when i write "make " after "cmake .." it gives the error below : 

> /home/elvan/fastMCD/src/main.hpp:25:16: fatal error: cv.h: No such file or directory
>  #include <cv.h>
>                 ^
> compilation terminated.
> CMakeFiles/fastMCD.dir/build.make:62: recipe for target 'CMakeFiles/fastMCD.dir/src/main.cpp.o' failed
> make[2]: *** [CMakeFiles/fastMCD.dir/src/main.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fastMCD.dir/all' failed
> make[1]: *** [CMakeFiles/fastMCD.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

I think there is a error that cmake doenst fınd libraries of opencv but i havent found any solution.

Please help me 
Thanks.

**Comment by kmyi** [comment]
This is probably too late, but it seems your opencv installation has issues. 

> CMake Warning at /home/elvan/opencv-2.4.12/cmake/OpenCVConfig.cmake:163 (message):
Found OpenCV Windows Pack but it has not binaries compatible with your
configuration.

You probably want to check there.

**Comment by hh2712** [comment]
@elvanduman71 As stated in your error, you will need to manually Cmake variable OpenCV_DIR to your build of OpenCV.
So add your build path of your opencv build directory in your CMakeLists.txt will do the job.

This what I added before find_package(OpenCV Required).

SET("OpenCV_DIR" "/home/administrator/opencv-3.1.0/build")
set(OpenCV_FOUND 1)

I

**Comment by jarekbiu** [comment]
Hi I have user ubuntu 16.04.2  x64 and opencv2.4.11.but I get some error when './fastMCD ../data/woman.mp4 0'   
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Please help me
Thanks.

**Comment by kmyi** [comment]
@jarekbiu That's probably an issue with your opencv install and the backend you've chosen. I can't help you much with that.

Also, I'm closing this issue, as it's more of an issue with OpenCV setup than the repo itself.
